config/routes.rb
Pixelserve::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount StripeEvent::Engine => '/stripe'

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :projects do
        member do
          put 'set_position'
          put 'toggle_favorite'
          put 'toggle_dashboard'
        end
        collection do
          put 'move'
        end
        resources :ctas
      end
      resources :videopages do
        member do
          get 'page'
          put 'save'
          put 'slug_save'
        end
      end
      resources :csns
      resources :assets do
        collection do
          get 'rackspace_streaming_url'
          get "upload_form_params"
        end
        member do
          get "copy_to_cloudfront"
          get "download_progress"
          get "encode_progress"
        end
      end
      resources :plans
      resources :folders
    end
  end

  namespace :account do
    root to: 'main#index'

    post 'create_customer' => "billing#create_customer"

    post "update_card" => "transactions#update_card"
    post "update_plan" => "transactions#update_plan"
    post "buy_addon" => "transactions#buy_addon"

    post "apply_coupon" => "subscriptions#apply_coupon"

    get "team" => "team_members#index"

    resources :users
    resources :team_members do
      collection do
        post "invite"
      end
    end
    resources :billing
    resources :subscriptions do
      member do
        get 'cancel'
      end
    end
  end

  resources :csns, only: [:index] do
    member do
      get "directories"
    end
  end

  resources :projects do
    get 'export', on: :collection
    get 'load_player_code'
  end
  resources :videopages do
    get 'preview'
  end
  get '/videopage/:id' => 'videopages#edit'
  # match "/:user_url" => "videopages#real_preview"

  resources :getting_started, only: [:index, :destroy]
  resources :news, only: [:index, :count ,:show] do
    collection do
      get 'count'
    end
  end

  resources :accounts

  match '/news/detail' => 'news#detail'
  match 'dashboard' => 'main#dashboard'
  match 'help' => 'main#help'
  match 'csn_message' => 'main#csn_message'

  # get '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get


  root to: "main#dashboard"

  post "hide_welcome" => "main#hide_welcome"

  devise_for :users, :controllers => {
                                      :registrations => 'registrations',
                                      :passwords => "devise/passwords"
                                     }
  ActiveAdmin.routes(self)
end

app/controllers/account/main_controller.rb
class Account::MainController < AccountController
  respond_to :html

  skip_before_filter :check_ownership!, only: [:index]

  def index
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  respond_to :html

  skip_before_filter :authenticate_user!, only: [:home]

  def home
    if !current_user
      redirect_to new_user_session_path
    end
  end

  def dashboard
  end

  def help
  end

  def hide_welcome
    session[:hide_welcome] = true
    render nothing: true
  end

end

app/views/main/dashboard.html.haml
- content_for :title, "Dashboard"
%section(role="dashboard")
  #dashboard.page-body
    .row(ng-controller="GuideStepsCtrl" ng-show="visible()")
      .twelve.columns
        .starting.steps.clearfix
          .col1.pull-left
            %h3 Getting Started?
            %p Go though these 10 simple steps to see how OptimizePlayer works
          .col2.pull-right
            = image_tag "arrow-dashboard.png", class: "arrow"
            %ul.navigation
              %li(ng-repeat=" task in tasks " style="padding: 0 2px")
                %a(href="" ng-class="{active : isSelected(task)}" ng-click="setTask( task )")
            .step(ng-class="{active : isSelected(task)}" ng-repeat=" task in tasks ")
              %h4
                %input.pretty(name="terms_conditions" ng-click="finishTask(task)" type="checkbox")/
                / <i class="picon-checkbox-false"></i>
                {{ task.title }}
              %p {{ task.short_description }}
              %a.more.button.radius.blue(ng-href="{{task.url}}") Read more
    .row(ng-controller="DashboardCtrl")
      .eight.columns.projects
        .box
          .header.clearfix
            %ul.menu.pull-left
              %li.tab1(ng-class= "{'active': tooltips.tab == 1}")
                %a(ng-click="tooltips.tab = 1" href="#" eat-click)
                  %i.icon-heart
                  Favourites
              %li.tab2(ng-class= "{'active': tooltips.tab == 2}")
                %a(ng-click="tooltips.tab = 2" href="#" eat-click)
                  %i.icon-time.icon-large
                  Recent Projects
              %li.tab3(ng-class= "{'active': tooltips.tab == 3}")
                %a(ng-click="tooltips.tab = 3" href="#" eat-click)
                  %i.icon-plane.icon-large
                  New Projects
            .pull-right
              %a.help(href="#") ?
          .body.projects.favorites
            .box-tab.box-tab1(ng-class= "{'active': tooltips.tab == 1}")
              %ul.list
                %project-element(ng-cloak project="project" dashboard="true" favorites-resort="refreshFavorites" sync="tooltips" selectedIds="selectedIds" ng-repeat="project in favorites")
            .box-tab.box-tab2(ng-class= "{'active': tooltips.tab == 2}")
              %ul.list
                %project-element(ng-cloak project="project" dashboard="true" favorites-resort="refreshRecent" sync="tooltips" selectedIds="selectedIds" ng-repeat="project in recent")
            .box-tab.box-tab3(ng-class= "{'active': tooltips.tab == 3}")
              %ul.list
                %project-element(ng-cloak project="project" dashboard="true" favorites-resort="refreshNewest" sync="tooltips" selectedIds="selectedIds" ng-repeat="project in newest")
            .clearfix
      .four.columns.overview
        .box
          .header.clearfix
            .pull-left
              %h3
                %i.pbigicon-user
                Account Overview
            .pull-right
              %a.help(href="#") ?
          .body
            .usage
              = account_usage_bar(true)
              / .earn-embeds
              /   %i.picon-gift
              /   %a(href="#") Earn more Embeds
            - unless current_account.prepaid
              .current-plan
                %span
                  %b Current Plan
                %h4= current_account.subscription.plan.name
                %ul
                  - current_account.subscription.plan.features.each do |f|
                    - if f.present?
                      %li
                        %i.picon-ok
                        = raw f
                .centralize
                  = link_to "UPGRADE ACCOUNT", account_billing_index_path, class: "button radius"
                  %a.details(href="#") view details
    .row
      .twelve.columns
        .updates.steps.clearfix
          .col1.pull-left
            %h3 Latest Updates
            %p OptimizePlayer system updates
          %div(ng-controller="NewsCountCtrl")
            .col2.pull-right
              = image_tag "arrow-dashboard.png", class: "arrow"
              %ul.navigation
                %li(ng-repeat=" n in news " style="padding: 0 2px")
                  %a(href="" ng-class="{active : isSelected(n)}" ng-click="setTask( n )")
              .step(ng-class="{active : isSelected(n)}" ng-repeat=" n in news ")
                .clearfix
                  .pull-left
                    %h4
                      %a(href="/news/{{n.id}}") {{n.title}}
                  .pull-right.date
                    Published:
                    %b {{n.created_at | date:'MM/dd/yyyy'}}
                    Category:
                    %a(href="#") News
                %p(ng-bind-html-unsafe="n.body | cut:true:200:' ...'" ng-hide="lessEnabled")
                %a.more.button.radius.blue(href="/news/{{n.id}}") {{rBtnContent}}
          /
            div class="col2 pull-right">
            <haml_silent>
            </haml_silent>            <ul class="navigation">
            <haml_silent>
            </haml_silent>
            <li><a href="#" data-step="step</haml_block><haml_silent></haml_silent><haml_block>"></a></li>
            
            <haml_silent>
            </haml_silent>            </ul>
            <haml_silent>
            </haml_silent>            <div class="step step</haml_block><haml_silent></haml_silent><haml_block> </haml_block><haml_silent></haml_silent><haml_block>">
            <div class="clearfix">
            <div class="pull-left"><h4>How to connect to a CSN </haml_block><haml_silent></haml_silent><haml_block></h4></div>
            <div class="pull-right date">Published: <b>13/03/2013</b> Category: <a href="#">News</a></div>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis facilisis lobortis. Aliquam vitae varius arcu. Nam consequat lacus et mauris semper, a venenatis nisi accumsan.</p>
            <a href="#" class="more button radius blue">Read more</a>
            </div>
            <haml_silent>
            </haml_silent>          </div>
            </div>
            </div

app/views/main/help.html.haml
- content_for :title, "Help"
%section#help(role="help")
  .page-body
    .row.knowledgebase
      .twelve.columns
        %iframe(src="http://help.optimizeplayer.com" width="100%" height="400" frameborder="0" scrolling="no" )