config/routes.rb
Pixelserve::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount StripeEvent::Engine => '/stripe'

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :projects do
        member do
          put 'set_position'
          put 'toggle_favorite'
          put 'toggle_dashboard'
        end
        collection do
          put 'move'
        end
        resources :ctas
      end
      resources :videopages do
        member do
          get 'page'
          put 'save'
          put 'slug_save'
        end
      end
      resources :csns
      resources :assets do
        collection do
          get 'rackspace_streaming_url'
          get "upload_form_params"
        end
        member do
          get "copy_to_cloudfront"
          get "download_progress"
          get "encode_progress"
        end
      end
      resources :plans
      resources :folders
    end
  end

  namespace :account do
    root to: 'main#index'

    post 'create_customer' => "billing#create_customer"

    post "update_card" => "transactions#update_card"
    post "update_plan" => "transactions#update_plan"
    post "buy_addon" => "transactions#buy_addon"

    post "apply_coupon" => "subscriptions#apply_coupon"

    get "team" => "team_members#index"

    resources :users
    resources :team_members do
      collection do
        post "invite"
      end
    end
    resources :billing
    resources :subscriptions do
      member do
        get 'cancel'
      end
    end
  end

  resources :csns, only: [:index] do
    member do
      get "directories"
    end
  end

  resources :projects do
    get 'export', on: :collection
    get 'load_player_code'
  end
  resources :videopages do
    get 'preview'
  end
  get '/videopage/:id' => 'videopages#edit'
  # match "/:user_url" => "videopages#real_preview"

  resources :getting_started, only: [:index, :destroy]
  resources :news, only: [:index, :count ,:show] do
    collection do
      get 'count'
    end
  end

  resources :accounts

  match '/news/detail' => 'news#detail'
  match 'dashboard' => 'main#dashboard'
  match 'help' => 'main#help'
  match 'csn_message' => 'main#csn_message'

  # get '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get


  root to: "main#dashboard"

  post "hide_welcome" => "main#hide_welcome"

  devise_for :users, :controllers => {
                                      :registrations => 'registrations',
                                      :passwords => "devise/passwords"
                                     }
  ActiveAdmin.routes(self)
end

app/views/layouts/_bottom_dropzone.html.haml
%section(role="dropzone")
  .tab-dropzone HIDE
  .dropzone
    .upload-box
      %form.upload-action(action="/dashboard" enctype="multipart/form-data" method="post")
        %input(name="token" type="hidden" value="")/
      %span
        = image_tag('/assets/icon-upload-white.png', :class => 'upload-icon')
        Drag your files to upload or
      %a.radius.button.blue.pc(href="#") Select from PC
      %a.radius.button.blue.csn(data-reveal-id="modal-csn" href="#" onclick="fileDestination='TESTE';")
        Select from CSN
      .upload-queue
        %span Uploading 1 of 3
        .progress.large-6.success.round
          %span.meter(style="width: 40%")
        %a(href="#")
          %i.picon-queue
        %a(href="#")
          %i.picon-new-white
        %a(href="#")
          %i.picon-close-white

app/views/layouts/_header.html.haml
%header(role="banner")
  .top-menu
    .row.wrapper
      .twelve.columns
        %nav
          .clearfix
            %ul.inline-list.pull-left
              %li
                %a.logo(href="/" ng-click="reloadRoot()")= image_tag "logo-small.png"
              %li
                .input-append.form-search.clearfix
                  %form(action="/projects" method="get")
                    %button(type="submit")
                      %i.picon-search
                    %input(name="search" placeholder="Search" type="text" value="#{@search}")/
            %ul.inline-list.pull-right
              %li
                %a.radius.button.green.more-embeds(href="#") Earn more embeds
              %li(user-dropdown="")
                %a.open-user-dropdown(href="")= gravatar_image_tag("#{current_user.email}".gsub('spam', 'mdeering'), :alt => "#{current_user.name}" , :gravatar => { :size => 31 })
                / a href class="open-user-dropdown"><haml_loud> image_tag &quot;temp-profile.png&quot;, width: &quot;25&quot; </haml_loud></a
                .user-dropdown
                  %ul
                    %li
                      %a(href="/account")
                        %i.picon-user-gray
                        Profile
                    - if current_user.owner
                      %li
                        %a(href="/account/billing")
                          %i.picon-billing-gray
                          Billing
                      %li
                        %a(href="/account/team")
                          %i.picon-team-gray
                          Teams
                      %li
                        %a(href="/csns")
                          %i.picon-connection-gray
                          Connections
                    %li
                      = link_to destroy_user_session_path do
                        %i.picon-logout-gray
                        Logout
  .main-menu 
    .row.wrapper
      .twelve.columns       
        %nav
          %ul.inline-list
            %li
              = link_to "Dashboard", dashboard_path, class: ("active" if current_page?(dashboard_path))
            %li
              %a(href="#") My Projects
              %ul
                %li.all-projects
                  = link_to "All Projects", projects_path, class: ("active" if current_page?(projects_path))
                %li.new-project
                  = link_to "New Project", new_project_path, class: ("active" if current_page?(new_project_path))
                %li.split-testing
                  %a(href="#") Split Testing

            %li
              %a(href="#") Analytics
            %li
              = link_to "Help", help_path, class: ("active" if current_page?(help_path))
            
            - if current_page? new_project_path
              %li#upload-button
                %a(href="#" data-reveal-id="upload-new-video") Upload Video

app/views/layouts/_page-header.html.haml
.page-header
  .row
    .twelve.columns.clearfix
      .pull-left
        .page-title= (yield(:title).blank?) ? 'My projects' : yield(:title)
      .pull-right
        .input-append.form-search.clearfix
          %form(action="/projects" method="get")
            %input(name="search" placeholder="Search projects..." type="text" value="#{@search}")/
            %button(type="submit")
              %i.pbigicon-search

app/views/layouts/application.html.haml
!!!
%html.no-js(ng-app="optimizePlayer")
  %head
    %meta(charset="utf-8")/
    %meta(content="IE=edge,chrome=1" http-equiv="X-UA-Compatible")/
    %title
    %meta(content="" name="description")/
    %meta(content="width=device-width" name="viewport")/
    = stylesheet_link_tag    "application", :media => "all"
    
    %link(href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700" rel="stylesheet" type="text/css")
    
    = csrf_meta_tags
    = yield :head
  %body
    = render partial: 'layouts/header'
    
    #main-content
      = yield
      
    = javascript_include_tag "application"
    %script(src="https://js.stripe.com/v2/" type="text/javascript")
    :javascript
      Stripe.setPublishableKey('STRIPE_PUBLIC_KEY');

app/views/layouts/devise.html.haml
!!!
%html(ng-app="optimizePlayer")
  %head
    %title OptimizePlayer
    %meta(content="width=device-width" name="viewport")/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    %link(rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700")
    
  %body#sign-in.centralize
    %header
    %section(role="sign-in")= yield
    %footer

app/views/layouts/embed.html.haml
!!!
%html
  %head
    %meta(charset="utf-8")/
    %meta(content="IE=edge,chrome=1" http-equiv="X-UA-Compatible")/
    %title
    %meta(content="" name="description")/
    %meta(content="width=device-width" name="viewport")/
    = stylesheet_link_tag "application", :media => "all" #FIXME
    = csrf_meta_tags
    = yield :head
  %body
    = yield

app/views/layouts/video_preview.html.haml
!!!
%html(ng-app="optimizePlayer")
  %head
    - if !@preview_page.blank?
      - if !@preview_page[:videopage][:seo].blank? && !@preview_page[:videopage][:seo][:title].blank?
        %title #{@preview_page[:videopage][:seo][:title]}
      - else
        %title Video preview
      - if !@preview_page[:videopage][:seo].blank? && !@preview_page[:videopage][:seo][:keywords].blank?
        %meta{:name => "keywords", :content => @preview_page[:videopage][:seo][:keywords].join(", ") }
      - if !@preview_page[:videopage][:seo].blank? && !@preview_page[:videopage][:seo][:description].blank?
        %meta{:name => "description", :content => @preview_page[:videopage][:seo][:description]}
    = stylesheet_link_tag "application", :media => "all"
    - fonts_array = default_google_fonts
    - unless fonts_array.blank?
      - fonts_array.each do |font|
        = google_font_link_tag font
    = csrf_meta_tags
  / %body#video_preview(ng-controller="ProjectCtrl" role="projects")

  %body#video_preview{ :style=>"background: #{@preview_page and @preview_page[:videopage][:settings] and @preview_page[:videopage][:settings][:backgroundColor] ? @preview_page[:videopage][:settings][:backgroundColor] : '#fff' };"}
    = yield
    %footer
    = javascript_include_tag "application"